import { ToolDatabase } from './types';

export const toolDatabasePart11: ToolDatabase = {
  "Dating & Social Media": [
    { name: "222.app", url: "https://222.app", tags: ["dating", "social"] },
    { name: "Aisle", url: "https://aisle.co", tags: ["dating"] },
    { name: "Grindr (iOS)", url: "https://apps.apple.com/us/app/grindr-gay-chat/id319881193", tags: ["dating", "lgbtq"] },
    { name: "Happn (iOS)", url: "https://apps.apple.com/us/app/happn-dating-app/id918238771", tags: ["dating"] },
    { name: "OkCupid (iOS)", url: "https://apps.apple.com/us/app/okcupid-dating/id338701294", tags: ["dating"] },
    { name: "POF (iOS)", url: "https://apps.apple.com/us/app/pof-dating/id389388247", tags: ["dating"] },
    { name: "Tinder (iOS)", url: "https://apps.apple.com/us/app/tinder/id547702041", tags: ["dating"] },
    { name: "Badoo", url: "https://badoo.com", tags: ["dating"] },
    { name: "Bumble", url: "https://bumble.com", tags: ["dating"] },
    { name: "Bumble BFF", url: "https://bumble.com/bff", tags: ["social", "friends"] },
    { name: "Chispa", url: "https://chispa-app.com", tags: ["dating"] },
    { name: "Clover", url: "https://clover.co", tags: ["dating"] },
    { name: "Coffee Meets Bagel", url: "https://coffeemeetsbagel.com", tags: ["dating"] },
    { name: "Doublelist", url: "https://doublelist.com", tags: ["dating", "classifieds"] },
    { name: "Down App", url: "https://downapp.com", tags: ["dating"] },
    { name: "eHarmony", url: "https://eharmony.com", tags: ["dating"] },
    { name: "EliteSingles", url: "https://www.elitesingles.com", tags: ["dating"] },
    { name: "Emehive", url: "https://www.emehive.com", tags: ["dating"] },
    { name: "FarmersOnly", url: "https://www.farmersonly.com", tags: ["dating"] },
    { name: "FirstMet", url: "https://www.firstmet.com", tags: ["dating"] },
    { name: "FriendFinderX", url: "https://www.friendfinderx.com", tags: ["dating", "adult"] },
    { name: "Thursday", url: "https://www.getthursday.com", tags: ["dating"] },
    { name: "fbessez (GitHub)", url: "https://github.com/fbessez", tags: ["dev", "dating-tools"] },
    { name: "tomlandia (GitHub)", url: "https://github.com/tomlandia", tags: ["dev", "dating-tools"] },
    { name: "Grindr", url: "https://grindr.com", tags: ["dating", "lgbtq"] },
    { name: "Happn", url: "https://www.happn.com", tags: ["dating"] },
    { name: "Hater", url: "https://www.haterdater.com", tags: ["dating"] },
    { name: "Hiki", url: "https://www.hiki.com", tags: ["dating", "neurodivergent"] },
    { name: "Hily", url: "https://hily.com", tags: ["dating"] },
    { name: "Hinge", url: "https://hinge.co", tags: ["dating"] },
    { name: "HUD", url: "https://www.hud.app", tags: ["dating"] },
    { name: "IntelTechniques Tinder Guide", url: "https://inteltechniques.com/tinder.html", tags: ["osint", "tinder"] },
    { name: "JDate", url: "https://www.jdate.com", tags: ["dating"] },
    { name: "Kippo", url: "https://www.kippo.com", tags: ["dating", "gaming"] },
    { name: "LatinoPeopleMeet", url: "https://www.latinopeoplemeet.com", tags: ["dating"] },
    { name: "Lavalife", url: "https://www.lavalife.com", tags: ["dating"] },
    { name: "LesAmis", url: "https://www.lesamis.app", tags: ["dating"] },
    { name: "LightUp", url: "https://www.lightupapp.co", tags: ["dating"] },
    { name: "Lovoo", url: "https://www.lovoo.com", tags: ["dating"] },
    { name: "Lumen", url: "https://www.lumen.app", tags: ["dating", "senior"] },
    { name: "Mamba", url: "https://mamba.ru", tags: ["dating"] },
    { name: "Match.com", url: "https://match.com", tags: ["dating"] },
    { name: "Meet5", url: "https://www.meet5.app", tags: ["dating"] },
    { name: "MeetMe", url: "https://www.meetme.com", tags: ["dating"] },
    { name: "Meetic", url: "https://www.meetic.com", tags: ["dating"] },
    { name: "Meetville", url: "https://www.meetville.com", tags: ["dating"] },
    { name: "Mmoition", url: "https://www.mmoition.com", tags: ["dating"] },
    { name: "Muah.ai", url: "https://muah.ai", tags: ["ai", "companion"] },
    { name: "Mutual", url: "https://www.mutual.app", tags: ["dating"] },
    { name: "Muzmatch", url: "https://muzmatch.com", tags: ["dating"] },
    { name: "Nuit", url: "https://www.nuitapp.com", tags: ["dating"] },
    { name: "OkCupid", url: "https://okcupid.com", tags: ["dating"] },
    { name: "OurTime", url: "https://www.ourtime.com", tags: ["dating", "senior"] },
    { name: "Pickable", url: "https://pickable.co", tags: ["dating"] },
    { name: "Grindr (Android)", url: "https://play.google.com/store/apps/details?id=com.grindr.android", tags: ["dating", "lgbtq"] },
    { name: "Happn (Android)", url: "https://play.google.com/store/apps/details?id=com.happn", tags: ["dating"] },
    { name: "OkCupid (Android)", url: "https://play.google.com/store/apps/details?id=com.okcupid.okcupid", tags: ["dating"] },
    { name: "POF (Android)", url: "https://play.google.com/store/apps/details?id=com.pof.android", tags: ["dating"] },
    { name: "Tinder (Android)", url: "https://play.google.com/store/apps/details?id=com.tinder", tags: ["dating"] },
    { name: "POF", url: "https://pof.com", tags: ["dating"] },
    { name: "POF Advanced Search", url: "https://www.pof.com/advancedsearch.aspx", tags: ["osint", "dating"] },
    { name: "Pure", url: "https://www.pure.app", tags: ["dating"] },
    { name: "Raya", url: "https://www.rayaapp.com", tags: ["dating", "exclusive"] },
    { name: "Reddit Affairs", url: "https://www.reddit.com/r/Affairs/", tags: ["reddit", "dating"] },
    { name: "Reddit AlienExchange", url: "https://www.reddit.com/r/AlienExchange/", tags: ["reddit", "dating"] },
    { name: "Reddit CuddleBuddies", url: "https://www.reddit.com/r/cuddlebuddies/", tags: ["reddit", "dating"] },
    { name: "Reddit DatingOverThirty", url: "https://www.reddit.com/r/datingoverthirty/", tags: ["reddit", "dating"] },
    { name: "Reddit ForeverAloneDating", url: "https://www.reddit.com/r/ForeverAloneDating/", tags: ["reddit", "dating"] },
    { name: "Reddit Grindr", url: "https://www.reddit.com/r/grindr/", tags: ["reddit", "dating"] },
    { name: "Reddit Happn", url: "https://www.reddit.com/r/happn/", tags: ["reddit", "dating"] },
    { name: "Reddit HardshipMates", url: "https://www.reddit.com/r/hardshipmates/", tags: ["reddit", "dating"] },
    { name: "Reddit Hookup", url: "https://www.reddit.com/r/hookup/", tags: ["reddit", "dating"] },
    { name: "Reddit InternetFriends", url: "https://www.reddit.com/r/InternetFriends/", tags: ["reddit", "social"] },
    { name: "Reddit KikPals", url: "https://www.reddit.com/r/Kikpals/", tags: ["reddit", "social"] },
    { name: "Reddit LetsChat", url: "https://www.reddit.com/r/LetsChat/", tags: ["reddit", "social"] },
    { name: "Reddit MakeNewFriendsHere", url: "https://www.reddit.com/r/MakeNewFriendsHere/", tags: ["reddit", "social"] },
    { name: "Reddit NSFWskype", url: "https://www.reddit.com/r/NSFWskype/", tags: ["reddit", "adult"] },
    { name: "Reddit nycr4r", url: "https://www.reddit.com/r/nycr4r/", tags: ["reddit", "dating"] },
    { name: "Reddit OkCupid", url: "https://www.reddit.com/r/OkCupid/", tags: ["reddit", "dating"] },
    { name: "Reddit OlderWomen", url: "https://www.reddit.com/r/olderwomen/", tags: ["reddit", "dating"] },
    { name: "Reddit OnlineDating", url: "https://www.reddit.com/r/OnlineDating/", tags: ["reddit", "dating"] },
    { name: "Reddit Penpals", url: "https://www.reddit.com/r/penpals/", tags: ["reddit", "social"] },
    { name: "Reddit PolyamoryR4R", url: "https://www.reddit.com/r/polyamoryR4R/", tags: ["reddit", "dating"] },
    { name: "Reddit Tinder", url: "https://www.reddit.com/r/Tinder/", tags: ["reddit", "dating"] },
    { name: "RomanceScams.org", url: "https://www.romancescams.org", tags: ["security", "scams"] },
    { name: "OkCupid Scams Guide", url: "https://www.romancescams.org/okcupid-scams/", tags: ["security", "scams"] },
    { name: "SawYouAtSinai", url: "https://www.sawyouatsinai.com", tags: ["dating"] },
    { name: "Hacking Happn (SecJuice)", url: "https://www.secjuice.com/hacking-happn/", tags: ["security", "osint"] },
    { name: "OSINT Tinder Capture (SecJuice)", url: "https://www.secjuice.com/osint-advanced-tinder-capture/", tags: ["security", "osint"] },
    { name: "Singles50", url: "https://singles50.com", tags: ["dating", "senior"] },
    { name: "SoulSingles", url: "https://www.soulsingles.com", tags: ["dating"] },
    { name: "Spokeo", url: "https://www.spokeo.com", tags: ["people-search"] },
    { name: "SwipeHelper", url: "https://swipehelper.com", tags: ["dating", "tips"] },
    { name: "Taimi", url: "https://taimi.com", tags: ["dating", "lgbtq"] },
    { name: "Tantan", url: "https://tantan.com", tags: ["dating"] },
    { name: "Tastebuds.fm", url: "https://tastebuds.fm", tags: ["dating", "music"] },
    { name: "TechCrunch Dating Apps", url: "https://techcrunch.com/tag/dating-apps/", tags: ["news", "dating"] },
    { name: "TechCrunch Tinder", url: "https://techcrunch.com/tag/tinder/", tags: ["news", "tinder"] },
    { name: "The Blink Date", url: "https://www.theblinkdate.com", tags: ["dating"] },
    { name: "The Inner Circle", url: "https://theinnercircle.co", tags: ["dating"] },
    { name: "The League", url: "https://www.theleague.com", tags: ["dating"] },
    { name: "Timeleft", url: "https://www.timeleft.com", tags: ["social", "dinner"] },
    { name: "Tinder", url: "https://tinder.com", tags: ["dating"] },
    { name: "Tinder Desktop", url: "https://tinder.com/desktop", tags: ["dating"] },
    { name: "TurnUp", url: "https://turnupapp.com", tags: ["dating", "music"] },
    { name: "US Military Penpals", url: "https://www.usmilitarypenpals.com", tags: ["social", "military"] },
    { name: "Vice Online Dating", url: "https://www.vice.com/en/topic/online-dating", tags: ["news", "dating"] },
    { name: "Woo", url: "https://woo.in", tags: ["dating"] },
    { name: "Write A Prisoner", url: "https://www.writeaprisoner.com", tags: ["social", "prison"] },
    { name: "Meet An Inmate", url: "https://www.meet-an-inmate.com", tags: ["social", "prison"] },
    { name: "Wyzr", url: "https://www.wyzr.app", tags: ["dating"] },
    { name: "Yubo", url: "https://yubo.live", tags: ["social", "gen-z"] },
    { name: "Zoosk", url: "https://zoosk.com", tags: ["dating"] },
    { name: "BigOne", url: "https://www.bigone.dating", tags: ["dating"] },
    { name: "Dinky Dating", url: "https://www.dinkydating.com", tags: ["dating"] },
    { name: "BBW Cupid", url: "https://www.bbwcupid.com", tags: ["dating"] },
    { name: "Sexless Tribe", url: "https://www.sexlesstribe.com", tags: ["social"] },
    { name: "Cove", url: "https://www.coveapp.com", tags: ["dating"] },
    { name: "Club Pillar", url: "https://www.clubpillar.co", tags: ["dating"] },
    { name: "Dateability", url: "https://www.dateability.app", tags: ["dating", "disability"] },
    { name: "Caribbean Cupid", url: "https://www.caribbeancupid.com", tags: ["dating"] },
    { name: "BLK", url: "https://blk-app.com", tags: ["dating"] },
    { name: "BlackPeopleMeet", url: "https://www.blackpeoplemeet.com", tags: ["dating"] },
    { name: "Christian Mingle", url: "https://www.christianmingle.com", tags: ["dating"] },
    { name: "Consumer Reports Dating Sites", url: "https://www.consumerreports.org/dating-sites/", tags: ["reviews", "dating"] },
    { name: "DatingScout", url: "https://www.datingscout.com", tags: ["reviews", "dating"] },
    { name: "Wikipedia Dating Comparison", url: "https://en.wikipedia.org/wiki/Comparison_of_online_dating_websites", tags: ["wiki", "dating"] },
    { name: "OJP Tinder Investigation", url: "https://www.ojp.gov/ncjrs/virtual-library/abstracts/investigating-mobile-dating-applications-tinder-age", tags: ["research", "tinder"] },
    { name: "Pew Research Online Dating", url: "https://www.pewresearch.org/topic/internet-technology/online-dating/", tags: ["research", "dating"] },
    { name: "Police Chief Tinder Investigation", url: "https://www.policechiefmagazine.org/investigating-sexual-crime-in-the-tinder-age/", tags: ["research", "tinder"] },
    { name: "Statista Online Dating", url: "https://www.statista.com/topics/2158/online-dating/", tags: ["stats", "dating"] },
    { name: "Grindr Location Finding (Medium)", url: "https://medium.com/@johnnyxcchi/finding-a-users-location-on-grindr-the-simple-way-2e8f68d3538f", tags: ["osint", "grindr"] },
    { name: "Tinder Data Request (BuzzFeed)", url: "https://www.buzzfeednews.com/article/karrieschloss/i-asked-tinder-for-my-data", tags: ["privacy", "tinder"] },
    { name: "AdopteUnMec", url: "https://www.adopteunmec.com", tags: ["dating"] },
    { name: "LoveAwake", url: "https://www.loveawake.com", tags: ["dating"] },
    { name: "ToChat", url: "https://www.tochat.com", tags: ["social"] },
    { name: "Cupid Media", url: "https://www.cupidmedia.com", tags: ["dating"] },
    { name: "Curious Cat", url: "https://curiouscat.me", tags: ["social"] },
    { name: "DateMySchool", url: "https://www.datemyschool.com", tags: ["dating"] },
    { name: "Meetup Dating", url: "https://www.meetup.com/topics/dating-and-relationships/", tags: ["social", "dating"] },
    { name: "Facebook Dating", url: "https://www.facebook.com/dating", tags: ["dating"] },
    { name: "Feeld", url: "https://feeld.co", tags: ["dating", "kink"] },
    { name: "GoGetter", url: "https://www.gogetterapp.com", tags: ["dating"] },
    { name: "Hot or Not", url: "https://hotornot.com", tags: ["dating"] },
    { name: "Kik", url: "https://kik.com", tags: ["social"] },
    { name: "MyLOL", url: "https://mylol.com", tags: ["dating", "teen"] },
    { name: "Once", url: "https://once.app", tags: ["dating"] },
    { name: "S'More", url: "https://www.smore.app", tags: ["dating"] },
    { name: "SelfieYo", url: "https://selfieyo.com", tags: ["social"] },
    { name: "Tagged", url: "https://tagged.com", tags: ["social"] },
    { name: "TrulyMadly", url: "https://www.trulymadly.com", tags: ["dating"] },
    { name: "Fruitz", url: "https://fruitz.com", tags: ["dating", "gen-z"] },
    { name: "Snack", url: "https://snackapp.com", tags: ["dating", "gen-z"] },
    { name: "Feels", url: "https://feelsapp.com", tags: ["dating", "gen-z"] },
    { name: "Archer", url: "https://www.getarcherapp.com", tags: ["dating", "lgbtq"] },
    { name: "Blued", url: "https://blued.com", tags: ["dating", "lgbtq"] },
    { name: "Gaydar", url: "https://www.gaydar.net", tags: ["dating", "lgbtq"] },
    { name: "Growlr", url: "https://www.growlr.com", tags: ["dating", "lgbtq"] },
    { name: "HER", url: "https://weareher.com", tags: ["dating", "lgbtq"] },
    { name: "Hornet", url: "https://hornet.com", tags: ["dating", "lgbtq"] },
    { name: "Jack'd", url: "https://jackd.com", tags: ["dating", "lgbtq"] },
    { name: "Scruff", url: "https://scruff.com", tags: ["dating", "lgbtq"] },
    { name: "Lex", url: "https://lex.lgbt", tags: ["dating", "lgbtq"] },
    { name: "Sniffies", url: "https://sniffies.com", tags: ["dating", "lgbtq"] },
    { name: "Adam4Adam", url: "https://www.adam4adam.com", tags: ["dating", "lgbtq"] },
    { name: "Surge App", url: "https://surgeapp.com", tags: ["dating", "lgbtq"] },
    { name: "Manhunt", url: "https://manhunt.net", tags: ["dating", "lgbtq"] },
    { name: "Open", url: "https://www.open.app", tags: ["dating", "poly"] },
    { name: "AdultFriendFinder", url: "https://adultfriendfinder.com", tags: ["dating", "adult"] },
    { name: "Bender", url: "https://www.bender.io", tags: ["dating", "lgbtq"] },
    { name: "Meetup Polyamory", url: "https://www.meetup.com/topics/polyamory/", tags: ["social", "poly"] },
    { name: "Reddit Polyamory", url: "https://www.reddit.com/r/polyamory/", tags: ["reddit", "poly"] },
    { name: "3Fun", url: "https://3fun.app", tags: ["dating", "poly"] },
    { name: "PolyMatchMaker", url: "https://polymatchmaker.com", tags: ["dating", "poly"] },
    { name: "SwingLifeStyle", url: "https://www.swinglifestyle.com", tags: ["dating", "swingers"] },
    { name: "Alt.com", url: "https://www.alt.com", tags: ["dating", "bdsm"] },
    { name: "BDSMSingles", url: "https://bdsmsingles.com", tags: ["dating", "bdsm"] },
    { name: "Collapsace", url: "https://collapsace.com", tags: ["dating", "bdsm"] },
    { name: "Facebook BDSM Groups", url: "https://www.facebook.com/groups/1628468610499173", tags: ["social", "bdsm"] },
    { name: "Fetish.com", url: "https://www.fetish.com", tags: ["dating", "fetish"] },
    { name: "FetLife", url: "https://fetlife.com", tags: ["social", "bdsm"] },
    { name: "Fetster", url: "https://www.fetster.com", tags: ["social", "bdsm"] },
    { name: "FindAFemdom", url: "https://www.findafemdom.com", tags: ["dating", "bdsm"] }
  ]
};
