import { ToolDatabase } from './types';

export const toolDatabasePart10: ToolDatabase = {
  "Artificial Intelligence (AI) & LLMs": [
    { name: "Ryver.ai", url: "https://ryver.ai", tags: ["ai", "productivity"] },
    { name: "LetMeDoIt.ai", url: "https://letmedoit.ai", tags: ["ai", "assistant"] },
    { name: "LiteLLM.ai", url: "https://litellm.ai", tags: ["ai", "llm", "api"] },
    { name: "ClaerityAI", url: "https://claerityai.com", tags: ["ai", "voice"] },
    { name: "Stability Matrix", url: "https://stabilitymatrix.org", tags: ["ai", "stable-diffusion"] },
    { name: "Wizi.ai", url: "https://wizi.ai", tags: ["ai", "coding"] },
    { name: "AI-Finder", url: "https://ai-finder.com", tags: ["ai", "directory"] },
    { name: "AIScout.net", url: "https://aiscout.net", tags: ["ai", "directory"] },
    { name: "There's An AI For That", url: "https://theresanaiforthat.com", tags: ["ai", "directory"] },
    { name: "FastStream.online", url: "https://faststream.online", tags: ["ai", "streaming"] },
    { name: "Nindo.com", url: "https://nindo.com", tags: ["ai", "social"] },
    { name: "Guru99", url: "https://guru99.com", tags: ["ai", "tutorial"] },
    { name: "CleanInsights.org", url: "https://cleaninsights.org", tags: ["ai", "analytics"] },
    { name: "Cipad.com", url: "https://cipad.com", tags: ["ai", "platform"] },
    { name: "Wize.bot", url: "https://wize.bot", tags: ["ai", "bot"] },
    { name: "ResumeTrick.com", url: "https://resumetrick.com", tags: ["ai", "resume"] },
    { name: "FusionBrain.ai", url: "https://fusionbrain.ai", tags: ["ai", "image"] },
    { name: "Bolt.new", url: "https://bolt.new", tags: ["ai", "coding", "web"] },
    { name: "Comma.ai", url: "https://comma.ai", tags: ["ai", "driving"] },
    { name: "Mistral AI", url: "https://mistral.ai", tags: ["ai", "llm"] },
    { name: "Secret Llama", url: "https://secretllama.com", tags: ["ai", "chat", "private"] },
    { name: "AnythingLLM", url: "https://anythingllm.com", tags: ["ai", "llm", "local"] },
    { name: "Fabric.so", url: "https://fabric.so", tags: ["ai", "productivity"] },
    { name: "Ptbk.io", url: "https://ptbk.io", tags: ["ai", "tool"] },
    { name: "Aler.ai", url: "https://aler.ai", tags: ["ai", "alert"] },
    { name: "Mochii.ai", url: "https://mochii.ai", tags: ["ai", "assistant"] },
    { name: "Together.ai", url: "https://together.ai", tags: ["ai", "cloud"] },
    { name: "PicMenu.co", url: "https://picmenu.co", tags: ["ai", "food"] },
    { name: "Smithery.ai", url: "https://smithery.ai", tags: ["ai", "mcp"] },
    { name: "Boltic.io", url: "https://boltic.io", tags: ["ai", "data"] },
    { name: "AIsplash.com", url: "https://aisplash.com", tags: ["ai", "images"] },
    { name: "Awwwards", url: "https://awwwards.com", tags: ["design", "awards"] },
    { name: "ToolPilot.ai", url: "https://toolpilot.ai", tags: ["ai", "directory"] },
    { name: "Vaiz.com", url: "https://vaiz.com", tags: ["ai", "video"] },
    { name: "Supermemory.ai", url: "https://supermemory.ai", tags: ["ai", "pkm"] },
    { name: "Kaggle", url: "https://kaggle.com", tags: ["ai", "data-science"] },
    { name: "LMArena.ai", url: "https://lmarena.ai", tags: ["ai", "benchmark"] },
    { name: "GoMoonbeam.com", url: "https://gomoonbeam.com", tags: ["ai", "writing"] },
    { name: "Copysmith.ai", url: "https://copysmith.ai", tags: ["ai", "copywriting"] },
    { name: "Jasper.ai", url: "https://jasper.ai", tags: ["ai", "writing"] },
    { name: "NanoGPT.com", url: "https://nanogpt.com", tags: ["ai", "chat"] },
    { name: "Chat2DB.ai", url: "https://chat2db.ai", tags: ["ai", "database"] },
    { name: "Anthropic", url: "https://anthropic.com", tags: ["ai", "llm", "claude"] },
    { name: "OpenFuture.ai", url: "https://openfuture.ai", tags: ["ai", "directory"] },
    { name: "SuperGPT.com", url: "https://supergpt.com", tags: ["ai", "chat"] },
    { name: "GPTGO.ai", url: "https://gptgo.ai", tags: ["ai", "search"] },
    { name: "Deepgram", url: "https://deepgram.com", tags: ["ai", "voice"] },
    { name: "AgentZero.ai", url: "https://agentzero.ai", tags: ["ai", "agents"] },
    { name: "1Intro.com", url: "https://1intro.com", tags: ["ai", "video"] },
    { name: "Automa.site", url: "https://automa.site", tags: ["ai", "automation"] },
    { name: "AIDark.net", url: "https://aidark.net", tags: ["ai", "directory"] },
    { name: "MiniApps.ai", url: "https://miniapps.ai", tags: ["ai", "apps"] },
    { name: "FastPix.io", url: "https://fastpix.io", tags: ["ai", "video"] },
    { name: "FlowGPT.com", url: "https://flowgpt.com", tags: ["ai", "prompts"] },
    { name: "BetterGPT.chat", url: "https://bettergpt.chat", tags: ["ai", "ui"] },
    { name: "1min.ai", url: "https://1min.ai", tags: ["ai", "productivity"] },
    { name: "GPT4.tools", url: "https://gpt4.tools", tags: ["ai", "tools"] },
    { name: "AIMagicX.com", url: "https://aimagicx.com", tags: ["ai", "tools"] },
    { name: "Fonio.ai", url: "https://fonio.ai", tags: ["ai", "audio"] },
    { name: "AI2UI.co", url: "https://ai2ui.co", tags: ["ai", "ui"] },
    { name: "Theta.tv", url: "https://theta.tv", tags: ["ai", "streaming", "crypto"] }
  ],
  "Cryptocurrency & Blockchain": [
    { name: "Shyft.to", url: "https://shyft.to", tags: ["crypto", "api"] },
    { name: "Siter.io", url: "https://siter.io", tags: ["crypto", "web"] },
    { name: "Figma.to.website", url: "https://figma.to.website", tags: ["crypto", "design"] },
    { name: "Slashpage.com", url: "https://slashpage.com", tags: ["crypto", "web"] },
    { name: "CryptoTrends.com", url: "https://cryptotrends.com", tags: ["crypto", "news"] },
    { name: "Blockworks.co", url: "https://blockworks.co", tags: ["crypto", "news"] },
    { name: "Wormholescan.io", url: "https://wormholescan.io", tags: ["crypto", "explorer"] },
    { name: "SaitaChain.com", url: "https://saitachain.com", tags: ["crypto", "blockchain"] },
    { name: "CryptoBubbles.net", url: "https://cryptobubbles.net", tags: ["crypto", "viz"] },
    { name: "OnionPlay.ch", url: "https://onionplay.ch", tags: ["crypto", "streaming"] },
    { name: "AlienFlix.com", url: "https://alienflix.com", tags: ["crypto", "streaming"] },
    { name: "LynxHub.com", url: "https://lynxhub.com", tags: ["crypto", "hub"] }
  ],
  "Streaming, IPTV & Live TV": [
    { name: "DevUploads.com", url: "https://devuploads.com", tags: ["streaming", "storage"] },
    { name: "TigoTago.com", url: "https://tigotago.com", tags: ["streaming", "tags"] },
    { name: "TuckTools.com", url: "https://tucktools.com", tags: ["streaming", "tools"] },
    { name: "Authme.levminer.com", url: "https://authme.levminer.com", tags: ["streaming", "auth"] },
    { name: "PixelChat.tv", url: "https://pixelchat.tv", tags: ["streaming", "chat"] },
    { name: "Xplorer.space", url: "https://xplorer.space", tags: ["streaming", "space"] },
    { name: "Screen-Play.app", url: "https://screen-play.app", tags: ["streaming", "screen"] },
    { name: "DashOne.app", url: "https://dashone.app", tags: ["streaming", "dashboard"] },
    { name: "BlackTwist.app", url: "https://blacktwist.app", tags: ["streaming", "app"] },
    { name: "ScheduleThreads.com", url: "https://schedulethreads.com", tags: ["streaming", "schedule"] },
    { name: "MetaCafe (VideosHub)", url: "https://metacafe.com", tags: ["streaming", "video"] },
    { name: "Dytt.app", url: "https://dytt.app", tags: ["streaming", "video"] },
    { name: "Pic8.co", url: "https://pic8.co", tags: ["streaming", "images"] },
    { name: "OneClickWeb.netlify.app", url: "https://oneclickweb.netlify.app", tags: ["streaming", "web"] }
  ],
  "Windows & General Utilities": [
    { name: "NirSoft", url: "https://nirsoft.net", tags: ["windows", "utilities"] },
    { name: "GetNotify.com", url: "https://getnotify.com", tags: ["email", "tracking"] },
    { name: "MorningStarSecurity.com", url: "https://morningstarsecurity.com", tags: ["security", "tools"] },
    { name: "DeskModder.com", url: "https://deskmodder.com", tags: ["windows", "customization"] },
    { name: "MakeUseOf", url: "https://makeuseof.com", tags: ["tech", "tips"] },
    { name: "AKUH.net", url: "https://akuh.net", tags: ["windows", "vps"] },
    { name: "CDM (Create Digital Music)", url: "https://cdm.link", tags: ["music", "tech"] },
    { name: "InfinityBots.com", url: "https://infinitybots.com", tags: ["bots", "discord"] },
    { name: "BotList.com", url: "https://botlist.com", tags: ["bots", "directory"] },
    { name: "Webtropia.com", url: "https://webtropia.com", tags: ["hosting", "vps"] },
    { name: "Jetstax.com", url: "https://jetstax.com", tags: ["dev", "tools"] },
    { name: "DownloadManager.com", url: "https://downloadmanager.com", tags: ["download", "manager"] },
    { name: "Elementary OS", url: "https://elementary.io", tags: ["linux", "os"] },
    { name: "Bliss OS", url: "https://blissos.org", tags: ["android", "os"] },
    { name: "Twake.app", url: "https://twake.app", tags: ["collaboration", "os"] },
    { name: "AllMyFaves.com", url: "https://allmyfaves.com", tags: ["directory", "links"] },
    { name: "FreeWeb3Resources.com", url: "https://freeweb3resources.com", tags: ["web3", "resources"] },
    { name: "System.com", url: "https://system.com", tags: ["search", "knowledge"] },
    { name: "Zorexeye.com", url: "https://zorexeye.com", tags: ["security", "tools"] },
    { name: "DeDigger.com", url: "https://dedigger.com", tags: ["file", "search"] },
    { name: "Cylect.io", url: "https://cylect.io", tags: ["osint", "tools"] },
    { name: "Converter-Now.web.app", url: "https://converter-now.web.app", tags: ["converter", "unit"] },
    { name: "SpyHackerz.org", url: "https://spyhackerz.org", tags: ["hacking", "forum"] },
    { name: "PiDeck.com", url: "https://pideck.com", tags: ["raspberry-pi", "dj"] },
    { name: "TinyPilot KVM", url: "https://tinypilotkvm.com", tags: ["kvm", "remote"] },
    { name: "PiApps.com", url: "https://piapps.com", tags: ["raspberry-pi", "apps"] },
    { name: "PiVPN.io", url: "https://pivpn.io", tags: ["raspberry-pi", "vpn"] },
    { name: "BerryBase.com", url: "https://berrybase.com", tags: ["raspberry-pi", "shop"] }
  ],
  "Security, Privacy & Hacking": [
    { name: "Nuclear.js.org", url: "https://nuclear.js.org", tags: ["privacy", "music"] },
    { name: "OpenStreamPlatform.com", url: "https://openstreamplatform.com", tags: ["privacy", "streaming"] },
    { name: "SpyHackerz.com", url: "https://spyhackerz.com", tags: ["hacking", "forum"] }
  ],
  "Design, Graphics & Fonts": [
    { name: "CoolText.com", url: "https://cooltext.com", tags: ["design", "text"] },
    { name: "UnlistedVideos.com", url: "https://unlistedvideos.com", tags: ["design", "video"] },
    { name: "Craftwork.design", url: "https://craftwork.design", tags: ["design", "assets"] },
    { name: "Snido.com", url: "https://snido.com", tags: ["design", "tools"] },
    { name: "JaxCore.com", url: "https://jaxcore.com", tags: ["design", "windows"] },
    { name: "Pussh.com", url: "https://pussh.com", tags: ["design", "links"] },
    { name: "AMPSuite.com", url: "https://ampsuite.com", tags: ["design", "music"] }
  ],
  "Search Engines (Meta, Social, Regional)": [
    { name: "InfinitySearch.co", url: "https://infinitysearch.co", tags: ["search", "privacy"] },
    { name: "QResearch.ch", url: "https://qresear.ch", tags: ["search", "research"] }
  ],
  "Server & Self-Hosted Tools": [
    { name: "Morphic.sh", url: "https://morphic.sh", tags: ["server", "automation"] },
    { name: "PiLeds.com", url: "https://pileds.com", tags: ["server", "led"] }
  ],
  "Awesome Lists & Resource Directories": [
    { name: "Awesome Audio Visualization", url: "https://github.com/willianjusten/awesome-audio-visualization", tags: ["list", "audio", "viz"] },
    { name: "Awesome Music Production", url: "https://github.com/m-p-c/awesome-music-production", tags: ["list", "music"] },
    { name: "Awesome Python", url: "https://github.com/vinta/awesome-python", tags: ["list", "python"] },
    { name: "Awesome Music Projects", url: "https://github.com/vincelwt/awesome-music-projects", tags: ["list", "music"] },
    { name: "Awesome OBS Plugin", url: "https://github.com/obsproject/obs-studio", tags: ["list", "obs"] },
    { name: "Awesome Design Plugins", url: "https://github.com/stefan-m-m/awesome-design-plugins", tags: ["list", "design"] },
    { name: "Awesome Design UI Kits", url: "https://github.com/stefan-m-m/awesome-design-ui-kits", tags: ["list", "design"] },
    { name: "BoardScriptz (BS)", url: "https://boardscriptz.org", tags: ["list", "scripts"] },
    { name: "Pandora (tool)", url: "https://github.com/pandora-analysis/pandora", tags: ["list", "analysis"] },
    { name: "Delightful", url: "https://github.com/delightful-dev/delightful", tags: ["list", "dev"] },
    { name: "Spotify Open Source Projects", url: "https://spotify.github.io", tags: ["list", "spotify"] },
    { name: "TheFUCK", url: "https://github.com/nvbn/thefuck", tags: ["list", "cli"] },
    { name: "The Hello World Collection", url: "https://github.com/leachim6/hello-world", tags: ["list", "code"] },
    { name: "MegaListofResources", url: "https://github.com/trimstray/the-book-of-secret-knowledge", tags: ["list", "resources"] },
    { name: "StreamDeck-Ui", url: "https://github.com/timothycrosley/streamdeck-ui", tags: ["list", "streamdeck"] },
    { name: "Open-Voice-Os", url: "https://github.com/OpenVoiceOS", tags: ["list", "voice", "os"] }
  ]
};
