import { ToolDatabase } from './types';

export const toolDatabasePart7: ToolDatabase = {
  "Spotify":[
    {name:"Spotify",url:"https://www.spotify.com",tags:["music"]}
  ],
  "Telegram":[
    {name:"Telegram",url:"https://telegram.org",tags:["messaging"]}
  ],
  "TikTok":[
    {name:"Mavekite",url:"https://mavekite.com",tags:["tiktok"]},
    {name:"Famety TikTok ID",url:"https://www.famety.net/find-tiktok-user-id",tags:["tiktok"]},
    {name:"Comment Picker ID",url:"https://commentpicker.com/tiktok-id.php",tags:["tiktok"]},
    {name:"Exolyt",url:"https://exolyt.com",tags:["tiktok"]},
    {name:"Bellingcat TikTok Timestamp",url:"https://bellingcat.github.io/tiktok-timestamp",tags:["tiktok"]},
    {name:"Analyst Research Tools",url:"https://analystresearchtools.com",tags:["tiktok"]},
    {name:"Trevor Fox TikTok Extractor",url:"https://trevorfox.com/tiktok-video-date-extractor",tags:["tiktok"]},
    {name:"DFIR Blog Unfurl",url:"https://dfir.blog/unfurl",tags:["tiktok"]},
    {name:"TikVib",url:"https://www.tikvib.com",tags:["tiktok"]},
    {name:"Urlebird",url:"https://urlebird.com",tags:["tiktok"]},
    {name:"TikFace",url:"https://www.tikface.com",tags:["tiktok"]},
    {name:"Famety Profile Pic",url:"https://www.famety.net/tiktok-profile-picture-size",tags:["tiktok"]},
    {name:"SSSTik",url:"https://ssstik.io",tags:["tiktok"]},
    {name:"TTSave",url:"https://ttsave.app",tags:["tiktok"]},
    {name:"TikFuel",url:"https://tikfuel.com",tags:["tiktok"]},
    {name:"TikTok Downloader",url:"https://tiktokdownloader.com",tags:["tiktok"]},
    {name:"SnapTik",url:"https://snaptik.app",tags:["tiktok"]},
    {name:"DDLVideo",url:"https://ddlvid.com",tags:["tiktok"]}
  ],
  "Twitch":[
    {name:"Twitch",url:"https://www.twitch.tv",tags:["streaming"]}
  ],
  "Twitter / X":[
    {name:"Followerwonk",url:"https://followerwonk.com",tags:["twitter"]},
    {name:"TweeterID",url:"https://tweeterid.com",tags:["twitter"]},
    {name:"BackTweets",url:"https://backtweets.com",tags:["twitter"]},
    {name:"Heavy.AI",url:"https://www.heavy.ai",tags:["analytics"]}
  ],
  "UK Vehicle Information":[
    {name:"CrashMap UK",url:"https://crashmap.co.uk",tags:["uk","vehicle"]},
    {name:"RoadCrash UK",url:"https://roadcrash.co.uk",tags:["uk","vehicle"]},
    {name:"Frixo",url:"https://frixo.com",tags:["uk","vehicle"]},
    {name:"Waze",url:"https://www.waze.com",tags:["nav"]},
    {name:"HPI Check",url:"https://www.hpicheck.com",tags:["uk","vehicle"]},
    {name:"RAC",url:"https://www.rac.co.uk",tags:["uk","vehicle"]},
    {name:"MyCarCheck",url:"https://www.mycarcheck.com",tags:["uk","vehicle"]},
    {name:"FullCarChecks",url:"https://fullcarchecks.co.uk",tags:["uk","vehicle"]},
    {name:"CarAnalytics",url:"https://caranalytics.co.uk",tags:["uk","vehicle"]},
    {name:"RapidCarCheck",url:"https://rapidcarcheck.co.uk",tags:["uk","vehicle"]},
    {name:"UltimateCarCheck",url:"https://ultimatecarcheck.co.uk",tags:["uk","vehicle"]},
    {name:"HowManyLeft",url:"https://howmanyleft.co.uk",tags:["uk","vehicle"]},
    {name:"VinDecoder.net",url:"https://vindecoder.net",tags:["vin"]},
    {name:"CarsOwners.net",url:"https://carsowners.net",tags:["forum"]},
    {name:"MIB",url:"https://www.mib.org.uk",tags:["uk","insurance"]},
    {name:"Vehicle Enquiry",url:"https://vehicleenquiry.service.gov.uk",tags:["uk","vehicle"]},
    {name:"MOT History",url:"https://check-mot.service.gov.uk",tags:["uk","vehicle"]},
    {name:"CarVeto",url:"https://carveto.co.uk",tags:["uk","vehicle"]},
    {name:"VehicleLookup",url:"https://vehiclelookup.uk",tags:["uk","vehicle"]},
    {name:"CheckTheCar",url:"https://checkthecar.com",tags:["uk","vehicle"]},
    {name:"CarTaxCheck",url:"https://cartaxcheck.co.uk",tags:["uk","vehicle"]},
    {name:"MotorScan",url:"https://motorscan.co.uk",tags:["uk","vehicle"]},
    {name:"CarTrail",url:"https://cartrail.co.uk",tags:["uk","vehicle"]},
    {name:"LiSense",url:"https://lisense.uk",tags:["uk","vehicle"]},
    {name:"MOT History Check",url:"https://check-mot-history.co.uk",tags:["uk","vehicle"]},
    {name:"CarValuation UK",url:"https://carvaluationuk.co.uk",tags:["uk","vehicle"]},
    {name:"London Tribunals",url:"https://www.londontribunals.org.uk",tags:["uk","parking"]},
    {name:"Plates4Less",url:"https://plates4less.co.uk",tags:["uk","plates"]},
    {name:"Elite Registrations",url:"https://eliteregistrations.co.uk",tags:["uk","plates"]},
    {name:"GOV.UK",url:"https://www.gov.uk",tags:["uk"]},
    {name:"Bikers United",url:"https://bikersunited.co.uk",tags:["uk","motorcycle"]},
    {name:"UK Campsite",url:"https://www.ukcampsite.co.uk",tags:["uk","stolen"]},
    {name:"TER Europe",url:"https://ter-europe.org",tags:["stolen"]},
    {name:"AutoTrader UK",url:"https://www.autotrader.co.uk",tags:["uk","vehicle"]},
    {name:"TotalCarCheck",url:"https://totalcarcheck.co.uk",tags:["uk","vehicle"]},
    {name:"TFL",url:"https://tfl.gov.uk",tags:["uk","transport"]},
    {name:"Castlepoint",url:"https://www.castlepoint.gov.uk",tags:["uk","taxi"]},
    {name:"Partial Number Plate",url:"https://partialnumberplate.co.uk",tags:["uk","plate"]},
    {name:"DriveArchive",url:"https://drivearchive.co.uk",tags:["uk","plate"]},
    {name:"Rate Driver",url:"https://rate-driver.co.uk",tags:["uk","driver"]},
    {name:"PlatesMania",url:"https://platesmania.com",tags:["plate"]},
    {name:"NCTS Ireland",url:"https://www.ncts.ie",tags:["ireland"]},
    {name:"MotorCheck Ireland",url:"https://www.motorcheck.ie",tags:["ireland"]},
    {name:"MyVehicle Ireland",url:"https://www.myvehicle.ie",tags:["ireland"]},
    {name:"Cartell Ireland",url:"https://www.cartell.ie",tags:["ireland"]},
    {name:"AA Ireland",url:"https://www.theaa.ie",tags:["ireland"]},
    {name:"DoneDeal Ireland",url:"https://www.donedeal.ie",tags:["ireland"]},
    {name:"World License Plates",url:"https://worldlicenseplates.com",tags:["plate"]},
    {name:"License Plate Mania",url:"https://licenseplatemania.com",tags:["plate"]},
    {name:"Tesla Map",url:"https://teslamap.io",tags:["tesla"]},
    {name:"Carnet.ai",url:"https://carnet.ai",tags:["ai","vehicle"]},
    {name:"Vercel",url:"https://vercel.app",tags:["hosting"]},
    {name:"Plate Recognizer",url:"https://platerecognizer.com",tags:["ai","plate"]}
  ],
  "Username / Specific Sites":[
    {name:"Amazon Usernames (M)",url:"https://www.google.com/search?q=site:amazon.com+%3Cusername%3E",tags:["dork"]},
    {name:"Github User (M)",url:"https://api.github.com/users/%3Cusername%3E/events/public",tags:["github"]},
    {name:"Keybase",url:"https://keybase.io/",tags:["keybase"]},
    {name:"MIT PGP Key Server",url:"http://pgp.mit.edu/",tags:["pgp"]},
    {name:"Room 101 Reddit Username (R)",url:"https://r00m101.com/",tags:["reddit"]},
    {name:"Tinder Usernames (M)",url:"https://www.gotinder.com/@%3Cusername%3E",tags:["tinder"]}
  ],
  "Username / Username Search Engines":[
    {name:"IDCrawl Username Search",url:"https://www.idcrawl.com/username",tags:["username"]},
    {name:"Instant Username Search",url:"https://instantusername.com/",tags:["username"]},
    {name:"NameCheckup",url:"https://namecheckup.com/",tags:["username"]},
    {name:"Namechk",url:"https://namechk.com/",tags:["username"]},
    {name:"Names Directory",url:"https://namesdir.com/",tags:["username"]},
    {name:"Sherlock (T)",url:"https://github.com/sherlock-project/sherlock",tags:["tool"]},
    {name:"Sylva Identity Discovery (T)",url:"https://sylva.pfeister.dev/",tags:["tool"]},
    {name:"Thats Them",url:"https://thatsthem.com/",tags:["people"]},
    {name:"UserSearch.org",url:"https://usersearch.org/",tags:["username"]},
    {name:"WhatsMyName",url:"https://whatsmyname.app/",tags:["username"]},
    {name:"WhatsMyName (T)",url:"https://github.com/WebBreacher/WhatsMyName",tags:["tool"]}
  ],
  "Username OSINT":[
    {name:"WhatsMyName",url:"https://whatsmyname.app",tags:["username"]},
    {name:"KnowEm",url:"https://knowem.com",tags:["username"]},
    {name:"UserSearch",url:"https://usersearch.org",tags:["username"]},
    {name:"Namechk",url:"https://namechk.com",tags:["username"]},
    {name:"NameCheckr",url:"https://namecheckr.com",tags:["username"]}
  ],
  "Utilities":[
    {name:"Wayback Machine",url:"https://archive.org",tags:["archive"]},
    {name:"TempMail",url:"https://temp-mail.org",tags:["utility"]},
    {name:"URLScan",url:"https://urlscan.io",tags:["analysis"]}
  ],
  "Vehicle Records":[
    {name:"Travic",url:"https://travic.org",tags:["transit"]},
    {name:"VinCheck.info",url:"https://www.vincheck.info",tags:["vin"]},
    {name:"VinDecoderz",url:"https://vindecoderz.com",tags:["vin"]},
    {name:"NICB VinCheck",url:"https://www.nicb.org/vincheck",tags:["vin"]}
  ],
  "Videos":[
    {name:"Bing Videos",url:"https://www.bing.com/videos",tags:["video"]},
    {name:"Blinkx",url:"https://www.blinkx.com",tags:["video"]},
    {name:"Dogpile",url:"https://www.dogpile.com",tags:["meta"]},
    {name:"Facebook Live",url:"https://www.facebook.com/live",tags:["facebook"]},
    {name:"Google Videos",url:"https://video.google.com",tags:["video"]},
    {name:"Internet Archive Movies",url:"https://archive.org/details/movies",tags:["archive"]},
    {name:"LiveLeak",url:"https://www.liveleak.com",tags:["video"]},
    {name:"Metatube",url:"https://www.metatube.com",tags:["video"]},
    {name:"Vimeo",url:"https://vimeo.com",tags:["video"]},
    {name:"Yahoo Video",url:"https://video.search.yahoo.com",tags:["video"]},
    {name:"ElevenLabs Dubbing",url:"https://elevenlabs.io/dubbing",tags:["ai"]},
    {name:"FRAPS",url:"https://fraps.com",tags:["screen"]},
    {name:"Greenshot",url:"https://getgreenshot.org",tags:["screen"]},
    {name:"ShareX",url:"https://getsharex.com",tags:["screen"]},
    {name:"Timeline Knightlab",url:"https://timeline.knightlab.com",tags:["timeline"]}
  ],
  "Virtual Machines and Linux Distros":[
    {name:"Kali Linux",url:"https://www.kali.org",tags:["distro"]},
    {name:"Parrot OS",url:"https://www.parrotsec.org",tags:["distro"]},
    {name:"Tails",url:"https://tails.net",tags:["distro"]},
    {name:"VirtualBox",url:"https://www.virtualbox.org",tags:["vm"]},
    {name:"VMware",url:"https://www.vmware.com",tags:["vm"]},
    {name:"Whonix",url:"https://www.whonix.org",tags:["distro"]},
    {name:"BlueStacks",url:"https://www.bluestacks.com",tags:["emulator"]},
    {name:"Genymotion",url:"https://www.genymotion.com",tags:["emulator"]},
    {name:"LDPlayer",url:"https://www.ldplayer.net",tags:["emulator"]},
    {name:"MEmu",url:"https://www.memuplay.com",tags:["emulator"]},
    {name:"NoxPlayer",url:"https://www.bignox.com",tags:["emulator"]}
  ],
  "Volunteering and CTF":[
    {name:"Night Owl Reconnaissance",url:"https://nightowlrecon.org/",tags:["volunteer"]},
    {name:"Trace Labs",url:"https://www.tracelabs.org/",tags:["ctf"]}
  ],
  "Webcams":[
    {name:"EarthCam",url:"https://www.earthcam.com",tags:["webcam"]},
    {name:"Insecam",url:"https://www.insecam.org",tags:["webcam"]}
  ],
  "Website Monitoring":[
    {name:"Anna's Archive",url:"https://annas-archive.org",tags:["archive"]},
    {name:"Archive.is",url:"https://archive.is",tags:["archive"]},
    {name:"Common Crawl",url:"https://commoncrawl.org",tags:["crawl"]},
    {name:"Wayback Machine",url:"https://web.archive.org",tags:["archive"]},
    {name:"PDF My URL",url:"https://pdfmyurl.com",tags:["pdf"]},
    {name:"Textfiles",url:"https://textfiles.com",tags:["archive"]},
    {name:"UK Web Archive",url:"https://www.webarchive.org.uk",tags:["archive"]},
    {name:"Burp Suite",url:"https://portswigger.net/burp",tags:["proxy"]},
    {name:"Fiddler",url:"https://www.fiddler2.com",tags:["proxy"]},
    {name:"Hunchly",url:"https://hunch.ly",tags:["capture"]},
    {name:"Wappalyzer",url:"https://wappalyzer.com",tags:["tech"]},
    {name:"WebPageTest",url:"https://www.webpagetest.org",tags:["perf"]},
    {name:"Censys",url:"https://censys.io",tags:["search"]},
    {name:"crt.sh",url:"https://crt.sh",tags:["cert"]},
    {name:"Google CT",url:"https://transparencyreport.google.com/https/certificates",tags:["cert"]},
    {name:"Netlas",url:"https://netlas.io",tags:["search"]},
    {name:"FollowThatPage",url:"https://www.followthatpage.com",tags:["monitor"]},
    {name:"VisualPing",url:"https://www.visualping.io",tags:["monitor"]},
    {name:"Shodan",url:"https://shodan.io",tags:["iot"]},
    {name:"URLScan",url:"https://urlscan.io",tags:["scan"]},
    {name:"DNSSEC Analyzer",url:"https://www.dnssec-analyzer.com",tags:["dns"]},
    {name:"DNSViz",url:"https://dnsviz.net",tags:["dns"]},
    {name:"Malware Domain List",url:"https://www.malwaredomainlist.com",tags:["malware"]},
    {name:"abuse.ch",url:"https://abuse.ch",tags:["threat"]},
    {name:"Shadowserver",url:"https://www.shadowserver.org",tags:["threat"]},
    {name:"DNSDumpster",url:"https://www.dnsdumpster.com",tags:["dns"]},
    {name:"SecurityTrails",url:"https://securitytrails.com",tags:["dns"]},
    {name:"AbuseIPDB",url:"https://www.abuseipdb.com",tags:["ip"]},
    {name:"AlienVault OTX",url:"https://otx.alienvault.com",tags:["threat"]},
    {name:"SenderBase",url:"https://www.senderbase.org",tags:["reputation"]},
    {name:"Google Safe Browsing",url:"https://safebrowsing.google.com",tags:["safe"]},
    {name:"Joe Sandbox",url:"https://www.joesandbox.com",tags:["sandbox"]},
    {name:"Sucuri SiteCheck",url:"https://sitecheck.sucuri.net/",tags:["security"]},
    {name:"ThreatMiner",url:"https://threatminer.org",tags:["threat"]},
    {name:"URLVoid",url:"https://www.urlvoid.com",tags:["reputation"]},
    {name:"URLQuery",url:"https://www.urlquery.net",tags:["scan"]},
    {name:"vURL",url:"https://www.vurl.com",tags:["scan"]},
    {name:"VirusTotal",url:"https://www.virustotal.com",tags:["scan"]},
    {name:"DNSstuff",url:"https://www.dnsstuff.com",tags:["dns"]},
    {name:"DomainTools Whois",url:"https://whois.domaintools.com",tags:["whois"]},
    {name:"EasyWhois",url:"https://www.easywhois.com",tags:["whois"]},
    {name:"Whoisology",url:"https://www.whoisology.com",tags:["whois"]},
    {name:"Robtex",url:"https://www.robtex.com",tags:["dns"]},
    {name:"ViewDNS",url:"https://viewdns.info",tags:["dns"]},
    {name:"Who.is",url:"https://who.is",tags:["whois"]},
    {name:"ARIN Whois",url:"https://whois.arin.net",tags:["whois"]}
  ],
  "WhatsApp":[
    {name:"WhatsApp",url:"https://www.whatsapp.com",tags:["messaging"]}
  ],
  "YouTube":[
    {name:"YouTube",url:"https://www.youtube.com",tags:["video"]},
    {name:"DetURL",url:"https://deturl.com",tags:["downloader"]},
    {name:"Hooktube",url:"https://hooktube.com",tags:["proxy"]},
    {name:"TubeChop",url:"https://www.tubechop.com",tags:["editor"]},
    {name:"Yasiv YouTube",url:"https://yasiv.com/youtube",tags:["visual"]},
    {name:"YouTube Data Tools",url:"https://tools.digitalmethods.net/netvizz/youtube",tags:["analysis"]}
  ]
};
