import { ToolDatabase } from './types';

export const toolDatabasePart16: ToolDatabase = {
  "Artificial Intelligence (AI) & LLMs": [
    { name: "Claude", url: "https://claude.ai", tags: ["ai", "llm", "anthropic"] },
    { name: "ChatGPT", url: "https://chatgpt.com", tags: ["ai", "llm", "openai"] },
    { name: "Gemini", url: "https://gemini.google.com", tags: ["ai", "llm", "google"] },
    { name: "DeepSeek", url: "https://chat.deepseek.com", tags: ["ai", "llm"] },
    { name: "Meta AI", url: "https://www.meta.ai", tags: ["ai", "llm", "meta"] },
    { name: "Perplexity", url: "https://perplexity.ai", tags: ["ai", "search"] },
    { name: "Phind", url: "https://www.phind.com", tags: ["ai", "search", "coding"] },
    { name: "Cursor", url: "https://cursor.so", tags: ["ai", "coding", "ide"] },
    { name: "Codeium", url: "https://codeium.com", tags: ["ai", "coding"] },
    { name: "Bito", url: "https://bito.ai", tags: ["ai", "coding"] },
    { name: "Codium", url: "https://www.codium.ai", tags: ["ai", "coding"] },
    { name: "Chatbot UI", url: "https://github.com/mckaywrigley/chatbot-ui", tags: ["ai", "ui", "open-source"] },
    { name: "ChatGPT Next Web", url: "https://github.com/Yidadaa/ChatGPT-Next-Web", tags: ["ai", "ui", "open-source"] },
    { name: "LobeChat", url: "https://lobechat.com", tags: ["ai", "ui", "open-source"] },
    { name: "Bing Image Creator", url: "https://www.bing.com/images/create", tags: ["ai", "image"] },
    { name: "Leonardo.ai", url: "https://leonardo.ai", tags: ["ai", "image"] },
    { name: "Adobe Firefly", url: "https://firefly.adobe.com", tags: ["ai", "image"] },
    { name: "Krea.ai", url: "https://www.krea.ai", tags: ["ai", "image"] },
    { name: "Ideogram", url: "https://ideogram.ai", tags: ["ai", "image"] },
    { name: "RunwayML", url: "https://runwayml.com", tags: ["ai", "video"] },
    { name: "Pika", url: "https://pika.art", tags: ["ai", "video"] },
    { name: "Pollinations", url: "https://pollinations.ai", tags: ["ai", "image", "generative"] },
    { name: "Vheer", url: "https://Vheer.com", tags: ["ai", "image"] },
    { name: "Fotor AI", url: "https://www.fotor.com", tags: ["ai", "image"] },
    { name: "Awesome ChatGPT Prompts", url: "https://github.com/f/awesome-chatgpt-prompts", tags: ["ai", "prompts"] },
    { name: "ChatDOC", url: "https://chatdoc.com", tags: ["ai", "documents"] },
    { name: "Humata", url: "https://www.humata.ai", tags: ["ai", "documents"] },
    { name: "Chatbase", url: "https://www.chatbase.co", tags: ["ai", "chatbot"] },
    { name: "NoCostAI", url: "https://nocostai.vercel.app/", tags: ["ai", "free"] },
    { name: "OpenRouter Rankings", url: "https://openrouter.ai/rankings", tags: ["ai", "leaderboard"] },
    { name: "Alpaca Eval", url: "https://tatsu-lab.github.io/alpaca_eval/", tags: ["ai", "leaderboard"] },
    { name: "Open LLM Leaderboard", url: "https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard", tags: ["ai", "leaderboard"] },
    { name: "Chatbot Arena", url: "https://huggingface.co/spaces/lmarena-ai/chatbot-arena-leaderboard", tags: ["ai", "leaderboard"] },
    { name: "MTEB Leaderboard", url: "https://huggingface.co/spaces/mteb/leaderboard", tags: ["ai", "leaderboard"] },
    { name: "Artificial Analysis", url: "https://artificialanalysis.ai/", tags: ["ai", "leaderboard"] },
    { name: "Yupp.ai Leaderboard", url: "https://yupp.ai/leaderboard", tags: ["ai", "leaderboard"] },
    { name: "G4F", url: "https://g4f.dev/", tags: ["ai", "api", "free"] },
    { name: "SharedChat", url: "https://sharedchat.cn", tags: ["ai", "chat"] },
    { name: "Groq", url: "https://groq.com", tags: ["ai", "inference"] },
    { name: "LumioAI", url: "https://app.lumioai.tech/", tags: ["ai", "chat"] },
    { name: "Mistral Chat", url: "https://chat.mistral.ai", tags: ["ai", "llm"] },
    { name: "Grok", url: "https://grok.com/chat", tags: ["ai", "llm", "xai"] },
    { name: "FlowGPT", url: "https://flowgpt.com/", tags: ["ai", "prompts"] },
    { name: "Pi", url: "https://pi.ai", tags: ["ai", "companion"] },
    { name: "Umint AI", url: "https://umint-ai.hf.space/", tags: ["ai", "chat"] },
    { name: "Mirexa", url: "https://mirexa.vercel.app/", tags: ["ai", "chat"] },
    { name: "AIChatGPTFree", url: "https://aichatgptfree.org/", tags: ["ai", "free"] },
    { name: "Heck.ai", url: "https://heck.ai", tags: ["ai", "chat"] },
    { name: "FreeGPT.es", url: "https://freegpt.es/", tags: ["ai", "free"] },
    { name: "FuckICoding", url: "https://link.fuckicoding.com/", tags: ["ai", "chat"] },
    { name: "DeepInfra", url: "https://deepinfra.com/chat", tags: ["ai", "inference"] },
    { name: "Kimi", url: "https://kimi.com", tags: ["ai", "llm"] },
    { name: "Copilot", url: "https://copilot.microsoft.com", tags: ["ai", "llm", "microsoft"] },
    { name: "TTSMP3", url: "https://ttsmp3.com", tags: ["ai", "audio", "tts"] },
    { name: "VoiceGenerator.io", url: "https://voicegenerator.io", tags: ["ai", "audio", "tts"] },
    { name: "FakeYou", url: "https://fakeyou.com", tags: ["ai", "audio", "tts"] },
    { name: "UncloseAI", url: "https://uncloseai.com/", tags: ["ai", "chat"] },
    { name: "Ollama", url: "https://ollama.com", tags: ["ai", "llm", "local"] },
    { name: "Poe", url: "https://poe.com", tags: ["ai", "chat"] },
    { name: "Writesonic", url: "https://writesonic.com/chat", tags: ["ai", "writing"] },
    { name: "Character.ai", url: "https://character.ai", tags: ["ai", "companion"] },
    { name: "Microsoft Designer", url: "https://designer.microsoft.com", tags: ["ai", "design"] },
    { name: "Suno", url: "https://suno.com", tags: ["ai", "music"] },
    { name: "Udio", url: "https://www.udio.com", tags: ["ai", "music"] },
    { name: "PixVerse", url: "https://app.pixverse.ai", tags: ["ai", "video"] },
    { name: "Genmo", url: "https://www.genmo.ai", tags: ["ai", "video"] },
    { name: "ElevenLabs", url: "https://elevenlabs.io", tags: ["ai", "audio", "voice"] },
    { name: "Stable Audio", url: "https://stableaudio.com", tags: ["ai", "audio", "music"] },
    { name: "Riffusion", url: "https://www.riffusion.com", tags: ["ai", "audio", "music"] },
    { name: "Uberduck", url: "https://www.uberduck.ai", tags: ["ai", "audio", "voice"] },
    { name: "Atlassian Rovo", url: "https://rovodevagents-beta.atlassian.net/wiki/external/OWEyMmMwZjllYjgyNDQzNjgyNWNiN2VhYjQ3MGY4MzI", tags: ["ai", "agents"] },
    { name: "Kiro.dev", url: "https://kiro.dev", tags: ["ai", "tools"] },
    { name: "IBM Watsonx", url: "https://www.ibm.com/products/watsonx-ai", tags: ["ai", "enterprise"] },
    { name: "AI SDK", url: "https://ai-sdk.dev", tags: ["ai", "dev"] },
    { name: "LLM7", url: "https://llm7.io/", tags: ["ai", "chat"] },
    { name: "Puter AI", url: "https://developer.puter.com/tutorials/free-unlimited-ai-api/", tags: ["ai", "api", "free"] },
    { name: "MyAI.asia", url: "https://myai.asia/", tags: ["ai", "chat"] }
  ]
};
