import { ToolDatabase } from './types';

export const toolDatabasePart9: ToolDatabase = {
  "Cryptocurrency & Blockchain": [
    { name: "Ethplorer", url: "https://ethplorer.io", tags: ["ethereum", "explorer"] },
    { name: "Chainlist.org", url: "https://chainlist.org", tags: ["evm", "networks"] },
    { name: "Cassandre", url: "https://cassandre.io", tags: ["crypto", "trading"] },
    { name: "Phantom.app", url: "https://phantom.app", tags: ["solana", "wallet"] },
    { name: "DEXTools.io", url: "https://dextools.io", tags: ["defi", "analytics"] },
    { name: "Swapter.io", url: "https://swapter.io", tags: ["crypto", "swap"] },
    { name: "paxful.com", url: "https://paxful.com", tags: ["p2p", "crypto"] },
    { name: "Storm.tg", url: "https://storm.tg", tags: ["telegram", "crypto"] },
    { name: "Solsnipper", url: "https://solsnipper.xyz", tags: ["solana", "sniper"] },
    { name: "Mango Markets", url: "https://mango.markets", tags: ["solana", "dex"] },
    { name: "CrowdSwap", url: "https://crowdswap.org", tags: ["defi", "cross-chain"] },
    { name: "Scan.0xscope.com", url: "https://scan.0xscope.com", tags: ["web3", "analytics"] },
    { name: "LiveCoinWatch", url: "https://livecoinwatch.com", tags: ["crypto", "prices"] },
    { name: "Honeygain", url: "https://honeygain.com", tags: ["passive", "income"] },
    { name: "Trustalabs.ai", url: "https://trustalabs.ai", tags: ["web3", "security"] },
    { name: "Cryptoflows.info", url: "https://cryptoflows.info", tags: ["crypto", "news"] },
    { name: "Tonmobile.com", url: "https://tonmobile.com", tags: ["ton", "mobile"] },
    { name: "Pawns", url: "https://pawns.app", tags: ["passive", "income"] },
    { name: "EarnApp", url: "https://earnapp.com", tags: ["passive", "income"] },
    { name: "Surge - P2P on steroids", url: "https://surge.sh", tags: ["p2p", "sharing"] },
    { name: "Token Terminal", url: "https://tokenterminal.com", tags: ["crypto", "data"] },
    { name: "1inch", url: "https://app.1inch.io", tags: ["dex", "aggregator"] },
    { name: "Thedecard.com", url: "https://thedecard.com", tags: ["crypto", "card"] },
    { name: "Crypto.com", url: "https://crypto.com", tags: ["crypto", "exchange"] },
    { name: "Wasabi Wallet", url: "https://wasabiwallet.io", tags: ["bitcoin", "privacy"] },
    { name: "Zcash", url: "https://z.cash", tags: ["privacy", "coin"] },
    { name: "BTCPay Server", url: "https://btcpayserver.org", tags: ["crypto", "payment"] },
    { name: "Instadapp.io", url: "https://instadapp.io", tags: ["defi", "management"] },
    { name: "Moontok", url: "https://moontok.io", tags: ["crypto", "listing"] },
    { name: "OKLink", url: "https://www.oklink.com", tags: ["blockchain", "explorer"] },
    { name: "Solana Beach", url: "https://solanabeach.io", tags: ["solana", "explorer"] }
  ],
  "Streaming, IPTV & Live TV": [
    { name: "m3u4u", url: "https://m3u4u.com", tags: ["iptv", "editor"] },
    { name: "Iptv-web.app", url: "https://iptv-web.app", tags: ["iptv", "player"] },
    { name: "Squid TV", url: "https://squidtv.net", tags: ["live", "tv"] },
    { name: "SatSupreme.com", url: "https://satsupreme.com", tags: ["satellite", "tv"] },
    { name: "RICHPLANET TV", url: "https://richplanet.tv", tags: ["alternative", "tv"] },
    { name: "Lossless-music.org", url: "https://lossless-music.org", tags: ["music", "lossless"] },
    { name: "FLAC Attack", url: "https://flacattack.net", tags: ["music", "flac"] },
    { name: "DJ-Source.com", url: "https://dj-source.com", tags: ["dj", "resources"] },
    { name: "Streamyfin.app", url: "https://streamyfin.app", tags: ["jellyfin", "client"] },
    { name: "Go2tv.app", url: "https://go2tv.app", tags: ["streaming", "tv"] },
    { name: "Sudo-Flix's Stremio Guide", url: "https://sudo-flix.github.io", tags: ["stremio", "guide"] },
    { name: "Pstream.org", url: "https://pstream.org", tags: ["streaming", "video"] },
    { name: "Kanopy", url: "https://www.kanopy.com", tags: ["movies", "library"] },
    { name: "DOKU-STREAMS.COM", url: "https://doku-streams.com", tags: ["documentaries", "streaming"] }
  ],
  "Awesome Livestreaming & Twitch Tools": [
    { name: "Macro Deck", url: "https://macrodeck.com", tags: ["stream", "deck"] },
    { name: "Elgato Marketplace", url: "https://www.elgato.com", tags: ["streaming", "gear"] },
    { name: "Streamscharts.com", url: "https://streamscharts.com", tags: ["streaming", "stats"] },
    { name: "Eklipse.gg", url: "https://eklipse.gg", tags: ["ai", "clipping"] },
    { name: "Livekit.io", url: "https://livekit.io", tags: ["webrtc", "stack"] },
    { name: "dev47apps", url: "https://dev47apps.com", tags: ["droidcam", "camera"] },
    { name: "Twitch Insights", url: "https://twitchinsights.com", tags: ["twitch", "stats"] },
    { name: "petpet", url: "https://petpet.io", tags: ["emote", "generator"] },
    { name: "Tangia", url: "https://tangia.co", tags: ["streaming", "interactions"] },
    { name: "kit.co", url: "https://kit.co", tags: ["gear", "list"] },
    { name: "Sidekick", url: "https://sidekick.gg", tags: ["streaming", "browser"] },
    { name: "eFuse.gg", url: "https://efuse.gg", tags: ["gaming", "social"] },
    { name: "Twitch tools by @CommanderRoot", url: "https://github.com/CommanderRoot/TwitchTools", tags: ["twitch", "tools"] },
    { name: "Twitch Overlay (alt)", url: "https://twitchoverlay.com", tags: ["twitch", "graphics"] },
    { name: "Twitch", url: "https://www.twitch.tv", tags: ["streaming", "platform"] }
  ],
  "Server & Self-Hosted Tools": [
    { name: "Contabo", url: "https://contabo.com", tags: ["vps", "hosting"] },
    { name: "netcup", url: "https://netcup.com", tags: ["vps", "hosting"] },
    { name: "Pi-KVM", url: "https://pikvm.org", tags: ["kvm", "raspberry-pi"] },
    { name: "Filestash", url: "https://filestash.app", tags: ["file", "manager"] },
    { name: "GrayLog", url: "https://graylog.org", tags: ["log", "management"] },
    { name: "Zipline", url: "https://zipline.diced.sh", tags: ["file", "sharing"] },
    { name: "Cloudflare", url: "https://cloudflare.com", tags: ["cdn", "security"] },
    { name: "WunderTech", url: "https://wundertech.net", tags: ["tech", "tutorials"] },
    { name: "Budibase", url: "https://budibase.com", tags: ["low-code", "platform"] },
    { name: "CapRover", url: "https://caprover.com", tags: ["paas", "self-hosted"] },
    { name: "Cloudron", url: "https://cloudron.io", tags: ["paas", "self-hosted"] },
    { name: "Appsmith", url: "https://appsmith.com", tags: ["internal", "tools"] },
    { name: "Airbyte", url: "https://airbyte.com", tags: ["data", "integration"] },
    { name: "Tiiny Host", url: "https://tiiny.host", tags: ["static", "hosting"] },
    { name: "MyAirBridge.com", url: "https://myairbridge.com", tags: ["file", "transfer"] },
    { name: "DropMeFiles", url: "https://dropmefiles.com", tags: ["file", "sharing"] },
    { name: "Syncany", url: "https://syncany.org", tags: ["file", "sync"] },
    { name: "Subrion CMS", url: "https://subrion.com", tags: ["cms", "php"] },
    { name: "Scribus", url: "https://scribus.net", tags: ["desktop", "publishing"] },
    { name: "Owncast (self-hosted streaming)", url: "https://owncast.online", tags: ["streaming", "self-hosted"] }
  ],
  "Search Engines (Meta, Social, Regional)": [
    { name: "Google", url: "https://google.com", tags: ["search", "general"] },
    { name: "Bing", url: "https://bing.com", tags: ["search", "general"] },
    { name: "Yandex", url: "https://yandex.com", tags: ["search", "russian"] },
    { name: "Yahoo", url: "https://yahoo.com", tags: ["search", "general"] },
    { name: "AOL", url: "https://aol.com", tags: ["search", "general"] },
    { name: "Ask", url: "https://ask.com", tags: ["search", "general"] },
    { name: "Dogpile", url: "https://dogpile.com", tags: ["search", "meta"] },
    { name: "Exalead", url: "https://exalead.com", tags: ["search", "enterprise"] },
    { name: "You.com", url: "https://you.com", tags: ["search", "ai"] },
    { name: "InfinitySearch", url: "https://infinitysearch.co", tags: ["search", "privacy"] },
    { name: "NAVER (KR)", url: "https://naver.com", tags: ["search", "korean"] },
    { name: "Qwant (FR)", url: "https://qwant.com", tags: ["search", "french"] },
    { name: "Pipilika (PH)", url: "https://pipilika.com", tags: ["search", "bengali"] },
    { name: "Satellite (RU)", url: "https://satellite.ru", tags: ["search", "russian"] },
    { name: "Mojek (UK)", url: "https://mojek.com", tags: ["search", "uk"] },
    { name: "Facebook", url: "https://facebook.com", tags: ["social", "search"] },
    { name: "LinkedIn", url: "https://linkedin.com", tags: ["social", "search"] },
    { name: "Twitter Search", url: "https://twitter.com/search", tags: ["social", "search"] },
    { name: "Pinterest", url: "https://pinterest.com", tags: ["social", "search"] },
    { name: "YouTube", url: "https://youtube.com", tags: ["video", "search"] },
    { name: "Dailymotion", url: "https://dailymotion.com", tags: ["video", "search"] },
    { name: "Vimeo", url: "https://vimeo.com", tags: ["video", "search"] },
    { name: "Twitch", url: "https://twitch.tv", tags: ["video", "search"] },
    { name: "PeerTube Search", url: "https://sepiasearch.org", tags: ["video", "search"] },
    { name: "d.tube Search", url: "https://d.tube", tags: ["video", "search"] },
    { name: "BitTube", url: "https://bittube.tv", tags: ["video", "search"] },
    { name: "BitChute", url: "https://bitchute.com", tags: ["video", "search"] },
    { name: "LBRY", url: "https://lbry.tv", tags: ["video", "search"] },
    { name: "Amazon Product Search", url: "https://amazon.com", tags: ["product", "search"] },
    { name: "WorldWideScience", url: "https://worldwidescience.org", tags: ["science", "search"] },
    { name: "CiteSeerX", url: "https://citeseerx.ist.psu.edu", tags: ["science", "search"] },
    { name: "NerdyData", url: "https://nerdydata.com", tags: ["code", "search"] },
    { name: "searchcode", url: "https://searchcode.com", tags: ["code", "search"] },
    { name: "StackShare", url: "https://stackshare.io", tags: ["tech", "stack"] },
    { name: "Pubmed", url: "https://pubmed.ncbi.nlm.nih.gov", tags: ["medical", "search"] },
    { name: "NAPALM FTP Indexer", url: "https://www.searchftps.net", tags: ["ftp", "search"] },
    { name: "QResearch", url: "https://qresear.ch", tags: ["research", "search"] }
  ],
  "Design, Graphics & Fonts": [
    { name: "Graffiti General", url: "https://graffitigeneral.com", tags: ["design", "graffiti"] },
    { name: "Glowtxt", url: "https://glowtxt.com", tags: ["design", "text"] },
    { name: "Graffiti Creator", url: "https://graffiticreator.net", tags: ["design", "graffiti"] },
    { name: "FreePNGImg", url: "https://freepngimg.com", tags: ["design", "png"] },
    { name: "PNGwing", url: "https://pngwing.com", tags: ["design", "png"] },
    { name: "Farbenfroh.io", url: "https://farbenfroh.io", tags: ["design", "colors"] },
    { name: "Linkero", url: "https://linkero.com", tags: ["design", "links"] },
    { name: "FSymbols", url: "https://fsymbols.com", tags: ["design", "symbols"] },
    { name: "Tint and Shade Generator", url: "https://tintandshade.com", tags: ["design", "colors"] },
    { name: "Metricool", url: "https://metricool.com", tags: ["social", "analytics"] },
    { name: "LogicalDOC", url: "https://logicaldoc.com", tags: ["document", "management"] },
    { name: "Cloudbrand", url: "https://cloudbrand.com", tags: ["branding", "cloud"] },
    { name: "TweetEraser", url: "https://tweeteraser.com", tags: ["twitter", "utility"] },
    { name: "Stathealth.io", url: "https://stathealth.io", tags: ["health", "stats"] },
    { name: "Neon tools", url: "https://neontools.io", tags: ["marketing", "tools"] },
    { name: "Nero Lens", url: "https://nero.com", tags: ["ai", "image"] },
    { name: "LiveSpace", url: "https://livespace.io", tags: ["streaming", "space"] },
    { name: "File Juggler", url: "https://filejuggler.com", tags: ["windows", "automation"] },
    { name: "VISUAL7", url: "https://visual7.com", tags: ["design", "visual"] },
    { name: "HypeAuditor", url: "https://hypeauditor.com", tags: ["influencer", "analytics"] }
  ],
  "Awesome Lists & Resource Directories": [
    { name: "Awesome Nocode Lowcode", url: "https://github.com/awesome-nocode/lowcode", tags: ["list", "no-code"] },
    { name: "Awesome Free Software", url: "https://github.com/awesome-foss/awesome-foss", tags: ["list", "foss"] },
    { name: "Awesome Self-Hosted", url: "https://github.com/awesome-selfhosted/awesome-selfhosted", tags: ["list", "self-hosted"] },
    { name: "Awesome Sysadmin", url: "https://github.com/awesome-foss/awesome-sysadmin", tags: ["list", "sysadmin"] },
    { name: "Awesome Public Datasets", url: "https://github.com/awesomedata/awesome-public-datasets", tags: ["list", "datasets"] },
    { name: "Awesome Discord", url: "https://github.com/discord/awesome-discord", tags: ["list", "discord"] },
    { name: "LibHunt", url: "https://libhunt.com", tags: ["software", "comparison"] },
    { name: "Sourceforge", url: "https://sourceforge.net", tags: ["software", "hosting"] },
    { name: "GitLab", url: "https://gitlab.com", tags: ["code", "hosting"] },
    { name: "FlatHub", url: "https://flathub.org", tags: ["linux", "apps"] },
    { name: "LinuxLinks", url: "https://linuxlinks.com", tags: ["linux", "resources"] },
    { name: "SlackBuilds.org", url: "https://slackbuilds.org", tags: ["slackware", "builds"] },
    { name: "Snapcraft", url: "https://snapcraft.io", tags: ["linux", "apps"] },
    { name: "Archlinux", url: "https://archlinux.org", tags: ["linux", "distro"] },
    { name: "Waydroid", url: "https://waydroid.org", tags: ["android", "linux"] },
    { name: "Jeedom", url: "https://jeedom.com", tags: ["smart-home", "os"] },
    { name: "Startpage", url: "https://startpage.com", tags: ["search", "privacy"] },
    { name: "Searx.space", url: "https://searx.space", tags: ["search", "meta"] }
  ]
};
