import { ToolDatabase } from './types';

export const toolDatabasePart8: ToolDatabase = {
  "Media & File Tools": [
    { name: "Wormhole", url: "https://wormhole.app", tags: ["file", "transfer"] },
    { name: "Capcut.com", url: "https://capcut.com", tags: ["video", "editor"] },
    { name: "FileMoon", url: "https://filemoon.sx", tags: ["file", "hosting"] },
    { name: "QRCode Monkey", url: "https://www.qr-code-monkey.com", tags: ["qr", "generator"] },
    { name: "DooDrive", url: "https://doodrive.com", tags: ["file", "storage"] },
    { name: "DigiMezzo", url: "https://www.digimezzo.com", tags: ["media", "player"] },
    { name: "ToffeeShare", url: "https://toffeeshare.com", tags: ["p2p", "file"] },
    { name: "Media.io", url: "https://media.io", tags: ["converter", "media"] },
    { name: "CloudConvert", url: "https://cloudconvert.com", tags: ["converter", "file"] },
    { name: "Filetransfer.io", url: "https://filetransfer.io", tags: ["file", "transfer"] },
    { name: "pixeldrain", url: "https://pixeldrain.com", tags: ["file", "sharing"] },
    { name: "Soldecoder.app", url: "https://soldecoder.app", tags: ["decoder", "tool"] },
    { name: "RustDesk", url: "https://rustdesk.com", tags: ["remote", "desktop"] },
    { name: "AppFlowy.IO", url: "https://appflowy.io", tags: ["notion", "alternative"] },
    { name: "StackBlitz", url: "https://stackblitz.com", tags: ["ide", "online"] },
    { name: "ClickUp", url: "https://clickup.com", tags: ["productivity", "tasks"] },
    { name: "Finddev.tools", url: "https://finddev.tools", tags: ["developer", "resources"] },
    { name: "privacytools.io", url: "https://privacytools.io", tags: ["privacy", "security"] },
    { name: "SimpleLogin", url: "https://simplelogin.io", tags: ["email", "alias"] },
    { name: "WebBrowserTools.com", url: "https://webbrowsertools.com", tags: ["browser", "testing"] },
    { name: "FreeWebToolkit", url: "https://freewebtoolkit.com", tags: ["tools", "online"] },
    { name: "Noted.lol", url: "https://noted.lol", tags: ["blog", "self-hosted"] },
    { name: "Manytools.org", url: "https://manytools.org", tags: ["tools", "online"] },
    { name: "FutureTools.io", url: "https://futuretools.io", tags: ["ai", "directory"] },
    { name: "Cisdem", url: "https://cisdem.com", tags: ["utility", "mac"] },
    { name: "Element Secure Chat", url: "https://element.io", tags: ["chat", "secure"] },
    { name: "Destream.net", url: "https://destream.net", tags: ["streaming", "donations"] },
    { name: "Probot.io", url: "https://probot.io", tags: ["discord", "bot"] },
    { name: "Jellysmack", url: "https://jellysmack.com", tags: ["content", "creator"] },
    { name: "ChitChat", url: "https://chitchat.gg", tags: ["chat", "random"] },
    { name: "Twitch Overlay", url: "https://twitchoverlay.com", tags: ["twitch", "graphics"] },
    { name: "Owncast", url: "https://owncast.online", tags: ["streaming", "self-hosted"] },
    { name: "Streamroutine.com", url: "https://streamroutine.com", tags: ["streaming", "tools"] },
    { name: "Taggy", url: "https://taggy.net", tags: ["tags", "generator"] },
    { name: "Lark", url: "https://lark.com", tags: ["collaboration", "office"] },
    { name: "7TV.APP", url: "https://7tv.app", tags: ["twitch", "emotes"] },
    { name: "CameraPro.io", url: "https://camerapro.io", tags: ["camera", "tools"] },
    { name: "Toolzu", url: "https://toolzu.com", tags: ["social", "tools"] },
    { name: "Watchpubs", url: "https://watchpubs.com", tags: ["publications", "watch"] },
    { name: "Dan.com", url: "https://dan.com", tags: ["domains", "marketplace"] },
    { name: "capacities.io", url: "https://capacities.io", tags: ["pkm", "notes"] },
    { name: "SharpTools", url: "https://sharptools.io", tags: ["smart-home", "dashboard"] },
    { name: "Synergy", url: "https://symless.com/synergy", tags: ["kvm", "software"] },
    { name: "Draw.io", url: "https://www.draw.io", tags: ["diagrams", "flowchart"] },
    { name: "FileCR", url: "https://filecr.com", tags: ["software", "downloads"] },
    { name: "Filepursuit", url: "https://filepursuit.com", tags: ["file", "search"] },
    { name: "Fileone.tv", url: "https://fileone.tv", tags: ["streaming", "video"] },
    { name: "Wolfstream.tv", url: "https://wolfstream.tv", tags: ["streaming", "video"] },
    { name: "WeMod", url: "https://wemod.com", tags: ["gaming", "mods"] },
    { name: "Quirklrapp.vercel.app", url: "https://quirklrapp.vercel.app", tags: ["app", "utility"] }
  ],
  "Artificial Intelligence (AI) & LLMs": [
    { name: "Jina AI", url: "https://jina.ai", tags: ["ai", "search"] },
    { name: "AutoGPT4All.sh", url: "https://autogpt4all.sh", tags: ["ai", "local"] },
    { name: "Shannonai.com", url: "https://shannonai.com", tags: ["ai", "nlp"] },
    { name: "TypingMind", url: "https://typingmind.com", tags: ["ai", "ui"] },
    { name: "Easy With AI", url: "https://easywithai.com", tags: ["ai", "directory"] },
    { name: "LocalAI", url: "https://localai.io", tags: ["ai", "local"] },
    { name: "Hugging Face", url: "https://huggingface.co", tags: ["ai", "models"] },
    { name: "FlowiseAI", url: "https://flowiseai.com", tags: ["ai", "no-code"] },
    { name: "Toolzz AI", url: "https://toolzz.ai", tags: ["ai", "tools"] },
    { name: "Topai.tools", url: "https://topai.tools", tags: ["ai", "directory"] },
    { name: "ClipFly", url: "https://clipfly.com", tags: ["ai", "video"] },
    { name: "Aitools.fyi", url: "https://aitools.fyi", tags: ["ai", "directory"] },
    { name: "AI Tool Hunt", url: "https://aitoolhunt.com", tags: ["ai", "directory"] },
    { name: "Kdenlive", url: "https://kdenlive.org", tags: ["video", "editor"] },
    { name: "Retool.com", url: "https://retool.com", tags: ["internal", "tools"] },
    { name: "erxes Inc", url: "https://erxes.io", tags: ["marketing", "os"] },
    { name: "MakeAGif", url: "https://makeagif.com", tags: ["gif", "creator"] },
    { name: "Anna-assistant", url: "https://anna-assistant.github.io", tags: ["ai", "assistant"] },
    { name: "ClamavNet", url: "https://clamav.net", tags: ["antivirus", "security"] },
    { name: "Appointment.day", url: "https://appointment.day", tags: ["scheduling", "tool"] },
    { name: "appery.io", url: "https://appery.io", tags: ["app", "builder"] },
    { name: "A.Tools", url: "https://a.tools", tags: ["ai", "tools"] },
    { name: "LunaPic.com", url: "https://lunapic.com", tags: ["image", "editor"] },
    { name: "FreeShow", url: "https://freeshow.app", tags: ["presentation", "software"] },
    { name: "DrawKit", url: "https://drawkit.com", tags: ["illustrations", "design"] },
    { name: "Voice Notepad", url: "https://voicenotepad.com", tags: ["speech-to-text", "voice"] },
    { name: "Pixsy", url: "https://pixsy.com", tags: ["image", "protection"] },
    { name: "ClipDrop", url: "https://clipdrop.co", tags: ["ai", "image"] },
    { name: "Spritemancer.com", url: "https://spritemancer.com", tags: ["sprite", "editor"] },
    { name: "ARCADE", url: "https://arcade.dev", tags: ["game", "dev"] },
    { name: "Notesnook", url: "https://notesnook.com", tags: ["notes", "private"] },
    { name: "Giflr", url: "https://giflr.com", tags: ["gif", "tool"] },
    { name: "Gofile", url: "https://gofile.io", tags: ["file", "sharing"] },
    { name: "O&O AppBuster", url: "https://oo-software.com/en/oandosupdater", tags: ["windows", "utility"] },
    { name: "Librechat.ai", url: "https://librechat.ai", tags: ["ai", "chat"] },
    { name: "Logo Design Generator", url: "https://logodesign.net", tags: ["logo", "design"] },
    { name: "Listmonk", url: "https://listmonk.app", tags: ["newsletter", "self-hosted"] },
    { name: "SVGcode", url: "https://svgco.de", tags: ["svg", "converter"] },
    { name: "Rave", url: "https://rave.dj", tags: ["music", "ai"] },
    { name: "if-me.org", url: "https://if-me.org", tags: ["mental-health", "os"] },
    { name: "ioBroker Smarthome", url: "https://iobroker.net", tags: ["smart-home", "os"] },
    { name: "Panzoid", url: "https://panzoid.com", tags: ["video", "intro"] },
    { name: "Unstoppable Domains", url: "https://unstoppabledomains.com", tags: ["web3", "domains"] },
    { name: "Shadertoy", url: "https://shadertoy.com", tags: ["graphics", "shaders"] },
    { name: "CyberChef", url: "https://gchq.github.io/CyberChef", tags: ["data", "swiss-army-knife"] },
    { name: "Pinocchio", url: "https://pinocchio.ai", tags: ["ai", "browser"] },
    { name: "Nmobile.nkn.org", url: "https://nmobile.nkn.org", tags: ["messaging", "d-app"] },
    { name: "Clippitt.app", url: "https://clippitt.app", tags: ["clipping", "tool"] },
    { name: "MATRIC", url: "https://matricapp.com", tags: ["pc", "control"] },
    { name: "Boosty", url: "https://boosty.to", tags: ["content", "monetization"] },
    { name: "Botrix.live", url: "https://botrix.live", tags: ["streaming", "bot"] },
    { name: "Rocket.Chat", url: "https://rocket.chat", tags: ["chat", "collaboration"] },
    { name: "PhotoMosh", url: "https://photomosh.com", tags: ["glitch", "art"] },
    { name: "Spikes Studio", url: "https://spikes.studio", tags: ["ai", "clipping"] },
    { name: "Realityripple.com", url: "https://realityripple.com", tags: ["software", "utility"] },
    { name: "Twir.app", url: "https://twir.app", tags: ["twitch", "bot"] },
    { name: "Sparkle.bot", url: "https://sparkle.bot", tags: ["discord", "bot"] },
    { name: "GitHub", url: "https://github.com", tags: ["code", "hosting"] },
    { name: "Twitch-chat-forwarder", url: "https://twitch-chat-forwarder.pages.dev", tags: ["twitch", "tool"] },
    { name: "Social Stream Ninja", url: "https://socialstream.ninja", tags: ["streaming", "social"] },
    { name: "stagetimer.io", url: "https://stagetimer.io", tags: ["timer", "stage"] },
    { name: "Linktree", url: "https://linktr.ee", tags: ["bio", "links"] },
    { name: "Overlays On", url: "https://overlayson.com", tags: ["streaming", "overlays"] },
    { name: "MrBoost Kick Widgets", url: "https://mrboost.io", tags: ["kick", "widgets"] },
    { name: "PRISM Live Studio", url: "https://prismlive.com", tags: ["streaming", "app"] },
    { name: "Flowframes", url: "https://flowframes.app", tags: ["ai", "interpolation"] },
    { name: "Codedao.ai", url: "https://codedao.ai", tags: ["ai", "coding"] },
    { name: "Pi, your personal AI", url: "https://pi.ai", tags: ["ai", "chat"] },
    { name: "Quasi.market", url: "https://quasi.market", tags: ["ai", "marketplace"] },
    { name: "Witto.es", url: "https://witto.es", tags: ["ai", "search"] },
    { name: "ResumeAI", url: "https://resumeai.com", tags: ["ai", "resume"] },
    { name: "Markwise.app", url: "https://markwise.app", tags: ["ai", "marketing"] },
    { name: "SillyTavern", url: "https://sillytavern.app", tags: ["ai", "roleplay"] },
    { name: "GPT4All", url: "https://gpt4all.io", tags: ["ai", "local"] },
    { name: "OpenRouter", url: "https://openrouter.ai", tags: ["ai", "api"] },
    { name: "Free-personal-ai-assistant", url: "https://free-personal-ai-assistant.streamlit.app", tags: ["ai", "assistant"] },
    { name: "Dreamily.ai", url: "https://dreamily.ai", tags: ["ai", "writing"] },
    { name: "Applio", url: "https://applio.org", tags: ["ai", "voice"] },
    { name: "Notebooklm", url: "https://notebooklm.google", tags: ["ai", "research"] },
    { name: "Mubert", url: "https://mubert.com", tags: ["ai", "music"] },
    { name: "Loudly", url: "https://loudly.com", tags: ["ai", "music"] },
    { name: "Stable Diffusion", url: "https://stability.ai", tags: ["ai", "image"] },
    { name: "Replica.ai", url: "https://replica.ai", tags: ["ai", "companion"] },
    { name: "Nansen", url: "https://nansen.ai", tags: ["crypto", "analytics"] },
    { name: "OpenBB", url: "https://openbb.co", tags: ["finance", "terminal"] },
    { name: "Vercel AI SDK", url: "https://sdk.vercel.ai", tags: ["ai", "dev"] },
    { name: "OpenArt", url: "https://openart.ai", tags: ["ai", "art"] },
    { name: "AIVA", url: "https://aiva.ai", tags: ["ai", "music"] },
    { name: "Black Ink", url: "https://blackink.ai", tags: ["ai", "tattoos"] },
    { name: "Playlistai.app", url: "https://playlistai.app", tags: ["ai", "music"] },
    { name: "ChatGate AI", url: "https://chatgate.ai", tags: ["ai", "chat"] },
    { name: "ComfyUI", url: "https://comfyui.org", tags: ["ai", "image"] },
    { name: "Sunnypilot.ai", url: "https://sunnypilot.ai", tags: ["ai", "driving"] },
    { name: "Voice Cloning Software", url: "https://voicecloning.com", tags: ["ai", "voice"] },
    { name: "ComfyUI Manager", url: "https://comfyui-manager.ma.pe", tags: ["ai", "tool"] }
  ],
  "AI Agents & Bots": [
    { name: "SwitchBot EU", url: "https://switchbot.eu", tags: ["smart-home", "bot"] },
    { name: "Convostack.ai", url: "https://convostack.ai", tags: ["ai", "stack"] },
    { name: "Chaplin App", url: "https://chaplin.app", tags: ["ai", "bot"] },
    { name: "SQL Chat", url: "https://sqlchat.ai", tags: ["ai", "sql"] },
    { name: "ChuckGPT", url: "https://chuckgpt.ai", tags: ["ai", "chat"] },
    { name: "Freqtrade", url: "https://freqtrade.io", tags: ["crypto", "bot"] },
    { name: "Tawk.to", url: "https://tawk.to", tags: ["chat", "support"] },
    { name: "Easybot", url: "https://easybot.com", tags: ["ai", "bot"] },
    { name: "Notifyme.bot", url: "https://notifyme.bot", tags: ["notifications", "bot"] },
    { name: "Kicksomebot.com", url: "https://kicksomebot.com", tags: ["kick", "bot"] },
    { name: "Earkick.com", url: "https://earkick.com", tags: ["mental-health", "ai"] },
    { name: "Topbotlist.com", url: "https://topbotlist.com", tags: ["bot", "directory"] },
    { name: "AgentGPT", url: "https://agentgpt.reworkd.ai", tags: ["ai", "agents"] },
    { name: "Terminal GPT", url: "https://terminalgpt.com", tags: ["ai", "terminal"] },
    { name: "Chatgpt.js", url: "https://chatgpt.js.org", tags: ["ai", "js"] },
    { name: "Awesome-GPT-2", url: "https://github.com/OpenAccess-AI-Collective/awesome-gpt2", tags: ["ai", "list"] },
    { name: "Telechat.ai", url: "https://telechat.ai", tags: ["ai", "telegram"] },
    { name: "Gemini Pro Chat", url: "https://gemini.google.com", tags: ["ai", "google"] },
    { name: "Supermaven", url: "https://supermaven.com", tags: ["ai", "coding"] },
    { name: "Auto-GPT", url: "https://autogpt.net", tags: ["ai", "agents"] },
    { name: "LensGo", url: "https://lensgo.ai", tags: ["ai", "video"] },
    { name: "Llama-GPT", url: "https://llama-gpt.com", tags: ["ai", "local"] },
    { name: "ToolJet", url: "https://tooljet.com", tags: ["low-code", "internal"] }
  ],
  "News, Blogs & Magazines": [
    { name: "The New Stack", url: "https://thenewstack.io", tags: ["news", "tech"] },
    { name: "Superpower Daily", url: "https://superpowerdaily.com", tags: ["newsletter", "ai"] },
    { name: "Dom signal", url: "https://domsignal.com", tags: ["tech", "blog"] },
    { name: "Product Hunt", url: "https://producthunt.com", tags: ["products", "launch"] },
    { name: "Hackster", url: "https://hackster.io", tags: ["hardware", "blog"] },
    { name: "Medium", url: "https://medium.com", tags: ["blog", "platform"] },
    { name: "Brian Dorey Blog", url: "https://briandorey.com", tags: ["tech", "blog"] },
    { name: "CeoFix.Net", url: "https://ceofix.net", tags: ["windows", "tips"] },
    { name: "Trusted Reviews", url: "https://trustedreviews.com", tags: ["reviews", "tech"] },
    { name: "XtendedView", url: "https://xtendedview.com", tags: ["tech", "blog"] },
    { name: "Information is Beautiful", url: "https://informationisbeautiful.net", tags: ["data", "viz"] },
    { name: "SmartHomeBeginner", url: "https://smarthomebeginner.com", tags: ["smart-home", "blog"] },
    { name: "Mirror.xyz", url: "https://mirror.xyz", tags: ["web3", "blog"] },
    { name: "Electromaker.io", url: "https://electromaker.io", tags: ["hardware", "projects"] },
    { name: "Tutonaut", url: "https://tutonaut.de", tags: ["tech", "german"] },
    { name: "KitPloit", url: "https://kitploit.com", tags: ["security", "tools"] },
    { name: "BetaList", url: "https://betalist.com", tags: ["startups", "directory"] },
    { name: "Popular Mechanics", url: "https://popularmechanics.com", tags: ["science", "tech"] },
    { name: "HeiDoc.net", url: "https://heidoc.net", tags: ["windows", "iso"] },
    { name: "Windows Latest", url: "https://windowslatest.com", tags: ["windows", "news"] }
  ],
  "Windows & General Utilities": [
    { name: "Advanced Renamer", url: "https://www.advancedrenamer.com", tags: ["windows", "file"] },
    { name: "Wallpaper Engine Space", url: "https://wallpaperengine.space", tags: ["wallpaper", "engine"] },
    { name: "OpenDesktop", url: "https://opendesktop.org", tags: ["desktop", "os"] },
    { name: "HatsWP", url: "https://hatswp.com", tags: ["wordpress", "tips"] },
    { name: "RainbowTaskbar", url: "https://github.com/dragonGR/rainbowtaskbar", tags: ["windows", "ui"] },
    { name: "Flow Launcher", url: "https://flowlauncher.com", tags: ["windows", "launcher"] },
    { name: "Kickass Undelete", url: "https://kickassundelete.com", tags: ["file", "recovery"] },
    { name: "LocalSend", url: "https://localsend.org", tags: ["file", "transfer"] },
    { name: "Directory Opus", url: "https://www.gpsoft.com.au", tags: ["windows", "file"] },
    { name: "Wintotal", url: "https://wintotal.com", tags: ["windows", "utility"] },
    { name: "Wallpaper Abyss", url: "https://wallpaperabyss.com", tags: ["wallpaper", "images"] },
    { name: "Keyviz", url: "https://keyviz.com", tags: ["keystroke", "viz"] },
    { name: "PicView", url: "https://picview.org", tags: ["image", "viewer"] },
    { name: "Station", url: "https://station.app", tags: ["browser", "productivity"] },
    { name: "Winstall.app", url: "https://winstall.app", tags: ["windows", "apps"] },
    { name: "Meis Apps", url: "https://meisapps.com", tags: ["windows", "apps"] },
    { name: "Portapps", url: "https://portapps.io", tags: ["portable", "apps"] },
    { name: "Video Candy", url: "https://videocandy.com", tags: ["video", "tools"] },
    { name: "Datacopia.com", url: "https://datacopia.com", tags: ["data", "viz"] },
    { name: "ChartBlocks", url: "https://chartblocks.com", tags: ["chart", "builder"] },
    { name: "CleanSnap", url: "https://cleansnap.com", tags: ["screenshot", "clean"] },
    { name: "Kast.gg", url: "https://kast.gg", tags: ["watch", "party"] },
    { name: "LosslessCut", url: "https://losslesscut.app", tags: ["video", "editor"] },
    { name: "Snipaste", url: "https://snipaste.com", tags: ["screenshot", "tool"] },
    { name: "GridWM", url: "https://gridwm.com", tags: ["windows", "manager"] },
    { name: "PC Part Picker", url: "https://pcpartpicker.com", tags: ["hardware", "build"] },
    { name: "Neomailbox", url: "https://neomailbox.com", tags: ["email", "private"] },
    { name: "Ameliorated.io", url: "https://ameliorated.io", tags: ["windows", "iso"] },
    { name: "Windhawk", url: "https://windhawk.net", tags: ["windows", "customization"] },
    { name: "NetLimiter", url: "https://netlimiter.com", tags: ["network", "monitor"] },
    { name: "System Explorer", url: "https://systemexplorer.net", tags: ["windows", "utility"] },
    { name: "Simplewall", url: "https://simplewall.github.io", tags: ["firewall", "windows"] },
    { name: "Action!", url: "https://mirillis.com/en/products/action.html", tags: ["screen", "recorder"] },
    { name: "Zabbix", url: "https://www.zabbix.com", tags: ["monitoring", "network"] },
    { name: "Unified Remote", url: "https://www.unifiedremote.com", tags: ["remote", "control"] },
    { name: "Syncplay", url: "https://syncplay.pl", tags: ["watch", "party"] },
    { name: "FileHippo", url: "https://filehippo.com", tags: ["software", "downloads"] },
    { name: "FileHorse", url: "https://filehorse.com", tags: ["software", "downloads"] },
    { name: "AlternativeTo", url: "https://alternativeto.net", tags: ["software", "alternatives"] },
    { name: "Free Developer Stuff", url: "https://freestuff.dev", tags: ["dev", "free"] },
    { name: "Internet Archive", url: "https://archive.org", tags: ["archive", "web"] },
    { name: "Gum Road", url: "https://gumroad.com", tags: ["digital", "marketplace"] },
    { name: "Gamma", url: "https://gamma.app", tags: ["ai", "presentation"] },
    { name: "Videezy", url: "https://videezy.com", tags: ["stock", "video"] },
    { name: "Bloggif", url: "https://bloggif.com", tags: ["gif", "tools"] }
  ],
  "Security, Privacy & Hacking": [
    { name: "Online Vulnerability Scanners", url: "https://onlinescanners.com", tags: ["security", "scanner"] },
    { name: "The Exploit Database", url: "https://exploit-db.com", tags: ["exploit", "db"] },
    { name: "Omejo.com", url: "https://omejo.com", tags: ["security", "privacy"] },
    { name: "Whonix™", url: "https://www.whonix.org", tags: ["os", "privacy"] },
    { name: "Aircrack-ng", url: "https://www.aircrack-ng.org", tags: ["wifi", "security"] },
    { name: "NextDNS", url: "https://nextdns.io", tags: ["dns", "privacy"] },
    { name: "Sploitus", url: "https://sploitus.com", tags: ["exploit", "search"] },
    { name: "HiddenVM", url: "https://hiddenvm.org", tags: ["vm", "privacy"] },
    { name: "Spokeo", url: "https://www.spokeo.com", tags: ["people", "search"] },
    { name: "pentest-tools", url: "https://pentest-tools.com", tags: ["pentest", "online"] },
    { name: "Research Clinic", url: "https://researchclinic.com", tags: ["osint", "tools"] },
    { name: "Ethical Hacking (Reddit)", url: "https://reddit.com/r/hacking", tags: ["reddit", "hacking"] },
    { name: "Hack-with-Github", url: "https://github.com/Hack-with-Github/Awesome-Hacking", tags: ["github", "list"] },
    { name: "Carpedm20/awesome-hacking", url: "https://github.com/carpedm20/awesome-hacking", tags: ["github", "list"] },
    { name: "The Mango Zone", url: "https://themangozone.com", tags: ["security", "blog"] }
  ]
};
